#!perl

use 5.006;
use strict;
use warnings;

# generated by Dist::Zilla::Plugin::Author::SKIRMESS::RepositoryBase 0.033

use Test::EOL;

use lib::relative '../lib';
use Local::TestsDirs;

all_perl_files_ok( { trailing_whitespace => 1 }, grep { -d } qw( bin lib ), Local::TestsDirs::tests_dirs() );
