#!perl

use 5.006;
use strict;
use warnings;

# generated by Dist::Zilla::Plugin::Author::SKIRMESS::RepositoryBase 0.033

use FindBin qw($Bin);
use Test::Perl::Critic ( -profile => "$Bin/perlcriticrc-tests" );

use lib::relative '../lib';
use Local::TestsDirs;

all_critic_ok( Local::TestsDirs::tests_dirs() );
