package Local::TestsDirs;

use 5.006;
use strict;
use warnings;

# generated by Dist::Zilla::Plugin::Author::SKIRMESS::RepositoryBase 0.033

use FindBin qw($Bin);
use Path::Tiny;

sub tests_dirs {
    my @dirs = -d 't' ? ('t') : ();

    my $xt = -d 'xt' ? path('xt')->absolute->stringify : undef;
    my $xt_repo = path($Bin)->parent(2)->child('xt');
    if ( -d $xt_repo ) {
        $xt_repo = $xt_repo->absolute->stringify;
    }
    else {
        $xt_repo = undef;
    }

    return @dirs if !defined $xt && !defined $xt_repo;

    if ( defined $xt ) {
        push @dirs, 'xt';

        if ( defined $xt_repo && $xt ne $xt_repo ) {
            push @dirs, $xt_repo;
        }
    }
    else {
        push @dirs, $xt_repo;
    }

    return @dirs;
}

1;

# vim: ts=4 sts=4 sw=4 et: syntax=perl
